Repository Roshansuthar1105/Codify, pull requests merged in 2025-09, with the labels that each got.

#163 Adding Python Basics Content
  client/src/App.jsx
  client/src/pages/PythonNotes.jsx
Labels: gssoc25, Level 2

#180 Designed a logo and added it in client\src\ assets folder
  client/src/assets/codifylogo.png
Labels: enhancement, gssoc25, Level 1

#181 Added Google Oauth Login & Signup
  client/src/App.jsx
  client/src/pages/Login.jsx
  client/src/pages/OAuthCallback.jsx
  client/src/pages/Signup.jsx
  server/.env.example
  server/config/passport.js
  server/controllers/authController.js
  server/models/userSchema.js
  server/package-lock.json
  server/package.json
  server/routes/authRouter.js
  server/server.js
Labels: enhancement, gssoc25, Level 3

#212 Redesign 404 Page to match Roadmaps page UI
  client/src/pages/ErrorPage.jsx
Labels: enhancement, gssoc25, Level 3

#248 Style : Redesign Footer Page to match Roadmaps UI
  client/src/components/Footer.jsx
Labels: enhancement, gssoc25, Level 3

#249 chore: rename LeaderBoardRoute.js and TodoRoute.js from PascalCase to camelCase for consistency
  server/routes/LeaderBoardRoute.js
  server/routes/leaderBoardRoute.js
  server/routes/todoRoute.js
  server/server.js
Labels: enhancement, gssoc25, Level 2

#247 feat : Update index.css
  client/src/index.css
Labels: enhancement, gssoc25, Level 2

#254 Enhance OTP email
  server/controllers/authController.js
  server/utils/OTPemailTemplates.js
  server/utils/sendEmail.js
Labels: enhancement, gssoc25, Level 2

#253 Question Page
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/MobileMenu.jsx
  client/src/components/PageHeader.jsx
  client/src/components/QuestionCard.jsx
  client/src/components/QuestionDetail.jsx
  client/src/components/QuestionsGrid.jsx
  client/src/context/QuestionContext.jsx
  client/src/main.jsx
  client/src/pages/QuestionPage.jsx
  package-lock.json
  package.json
Labels: enhancement, gssoc25, Level 3

#255 chore: update .env templates, README.md and refactor YouTube API key …
  README.md
  client/.env.example
  client/src/utils/youtubeUtils.js
  server/.env.example
Labels: enhancement, gssoc25, Level 2

#262 Create typescript.json
  client/src/assets/courses/typescript.json
Labels: enhancement, gssoc25, Level 2

#271 Refactored JS Fundamentals Notes Layout with Sidebar Navigation #243
  client/src/App.jsx
  client/src/assets/json/notes.json
  client/src/pages/JavaScriptFundamentals.jsx
  client/src/pages/Notes/GitVersionControl/GitNotes.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JavaScriptFundamentals.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsIntroduction.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/WhatAreVariables.jsx
  client/src/pages/Notes/JavaScriptFundamentals/components/JSNotes.json
  client/src/pages/Notes/JavaScriptFundamentals/components/JavaScriptNotesSideBar.jsx
  client/src/pages/Notes/JavaScriptFundamentals/components/JsHeroPage.jsx
  client/src/pages/Notes/JavaScriptFundamentals/components/JsSideBarData.json
  client/src/pages/Notes/PythonBasics/PythonNotes.jsx
  client/src/pages/Notes/ReactPatterns/ReactPattern.jsx
Labels: enhancement, gssoc25, Level 3

#270 Feature: Add Rust Course to the Courses Section
  client/src/assets/courses/rust.json
Labels: enhancement, gssoc25, Level 2

#286 Added best LLD courses link
  client/src/assets/courses/lld.json
Labels: enhancement, gssoc25, Level 2

#290 Added Pages for JavaScript Variables & Naming Rules
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/VariableNamingRules.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/WhatAreVariables.jsx
Labels: enhancement, gssoc25, Level 3

#291 Added Topics: Primitives & Objects, Operators & Expressions, Var vs Let vs Const
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/OperatorsAndExpressions.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/PrimitivesAndObjects.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/VarLetConst.jsx
Labels: enhancement, gssoc25, Level 3

#295 Added All JS Topic Imports & Replaced Code Blocks with CodeBlock.js Component
  client/src/pages/Notes/JavaScriptFundamentals/JavaScriptFundamentals.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Introduction/JsExecution.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Introduction/JsIntroduction.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Introduction/NodeJsInstallation.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsBasics/IfElseConditionals.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsBasics/IfElseLadder.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsBasics/SwitchCase.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsVariables/OperatorsAndExpressions.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsVariables/PrimitivesAndObjects.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsVariables/VarLetConst.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsVariables/VariableNamingRules.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsVariables/WhatAreVariables.jsx
  client/src/pages/Notes/JavaScriptFundamentals/components/CodeBlock.jsx
Labels: Style Enhancement, gssoc25, Level 3

#299 Added Copy Code Functionality to Code Blocks & Loader Overlay/Inline Toggle
  client/src/components/Loader.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JavaScriptFundamentals.jsx
  client/src/pages/Notes/JavaScriptFundamentals/components/CodeBlock.jsx
Labels: enhancement, gssoc25, Level 3

#284 removed the loader appearing while saving the card.
  client/src/App.jsx
  client/src/components/CardBody.jsx
  client/src/pages/Roadmap.jsx
Labels: enhancement, gssoc25, Level 3

#278 Validate email input in newsletter subscription form
  client/src/components/HomePageComponents/NewsLetter.jsx
Labels: enhancement, gssoc25, Level 2

#321 Added Routes for JS Topics & New Notes on Strings and Arrays
  client/src/pages/Notes/JavaScriptFundamentals/JavaScriptFundamentals.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/ArraysAndMethods.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/StringsInJS.jsx
Labels: enhancement, gssoc25, Level 3

#325 Added Topics: Numbers & Boolean in JavaScript
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/BooleanInJS.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/NumberInJS.jsx
Labels: enhancement, gssoc25, Level 3

#342 ufeat: add skill icons for enhanced roadmap visualization
  client/src/pages/Roadmap.jsx
Labels: enhancement, gssoc25, Level 3

#336 refactor loading state management from fetchWatchlist function
  client/src/pages/Courses.jsx
Labels: bug, gssoc25, Level 2

#377 Enhance ScrollToTop functionality
  client/src/App.jsx
Labels: bug, gssoc25, Level 2, frontend

#402 Refactor: Remove Lazy Loading, Standardize Notes Structure, Rebuild NotesPage with Motion Enhancements
  client/src/App.jsx
  client/src/pages/Notes/FallBackNotes.jsx
  client/src/pages/Notes/JavaScriptFundamentals/JavaScriptFundamentals.jsx
  client/src/pages/Notes/JavaScriptFundamentals/components/JsHeroPage.jsx
  client/src/pages/Notes/NotesData.js
  client/src/pages/Notes/NotesPage.jsx
  client/src/pages/NotesPage.jsx
Labels: enhancement, gssoc25, Level 3, frontend

#430 [ENHANCE] :enhance bg of icons on roadmap
  client/package-lock.json
  client/src/pages/Roadmap.jsx
Labels: enhancement, gssoc25, Level 2, frontend

#441 docs: add SECURITY.md for security practices
  SECURITY.md
Labels: documentation, gssoc25, Level 2

#442 added new feature clear console btn and shotcut keys for run and clear console
  client/src/App.jsx
  client/src/components/CodeEditor..jsx
  client/src/components/NavBar.jsx
Labels: gssoc25, Level 3, frontend

#465 Add Notes for Deleting Branches (git branch -d and git branch -D)
  client/src/pages/Notes/GitVersionControl/GitNotes.jsx
  client/src/pages/Notes/GitVersionControl/GitTopics/RemoteRepositories/GitPushPull.jsx
  client/src/pages/Notes/GitVersionControl/GitTopics/RemoteRepositories/GitRemoteAdd.jsx
  client/src/pages/Notes/GitVersionControl/GitTopics/RemoteRepositories/RemoteRepository.jsx
Labels: gssoc25, Level 3, frontend
