Repository Roshansuthar1105/Codify, pull requests merged in 2025-10, with the labels that each got.

#484 implement self-pinging mechanism with cron job
  server/package-lock.json
  server/package.json
  server/server.js
Labels: gssoc25, Level 2, backend

#492 Add Github OAuth
  client/src/App.jsx
  client/src/pages/Login.jsx
  client/src/pages/OAuthCallback.jsx
  server/.env.example
  server/config/passport.js
  server/controllers/authController.js
  server/models/userSchema.js
  server/package-lock.json
  server/package.json
  server/routes/authRouter.js
Labels: gssoc25, Level 3, frontend, backend, hacktoberfest

#499 Fix: fixed in styles for call to action to adhere color schema change.
  client/src/components/HomePageComponents/CallToAction.jsx
  client/src/components/HomePageComponents/Testimonials.jsx
Labels: enhancement, gssoc25, Level 2, hacktoberfest

#436 added sidebar + introduction page
  client/src/components/NavBar.jsx
  client/src/pages/Notes/ReactPatterns/ReactNotes/IntroductionToReactPatterns.jsx
  client/src/pages/Notes/ReactPatterns/ReactPattern.jsx
  client/src/pages/Notes/ReactPatterns/ReactSidebarPage.jsx
  client/src/pages/Notes/ReactPatterns/ReactTopics.jsx
Labels: gssoc25, Level 3, frontend, new-feature

#501 Added Datastructures Docs
  client/src/pages/Notes/PythonFundamentals/PyTopics/DataStructures/Dictionaries.jsx
  client/src/pages/Notes/PythonFundamentals/PyTopics/DataStructures/NestedLoops.jsx
  client/src/pages/Notes/PythonFundamentals/PyTopics/DataStructures/Strings.jsx
  client/src/pages/Notes/PythonFundamentals/PyTopics/DataStructures/TuplesSets.jsx
  client/src/pages/Notes/PythonFundamentals/PythonFundamentals.jsx
Labels: gssoc25, Level 3, frontend, hacktoberfest

#532 code language menu responsive 📱
  client/src/components/CodePlayground.jsx
  client/src/pages/CodeEditor.jsx
Labels: enhancement, gssoc25, Level 2, frontend, hacktoberfest
