Repository Roshansuthar1105/Codify, pull requests merged in 2025-08, with the labels that each got.

#45 Roadmaps: UI Enhancements, Search Functionality & JSON Update
  client/package-lock.json
  client/package.json
  client/src/assets/json/roadmap.json
  client/src/assets/json/skillbasedRoadmaps.json
  client/src/pages/Roadmap.jsx
Labels: duplicate, Style Enhancement, gssoc25, Level 3

#52 Added a new page of contributor guide and a new component in home page
  Readme.md
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/HomePageComponents/Contributor.jsx
  client/src/pages/ContributorGuide.jsx
  client/src/pages/Home.jsx
Labels: documentation, enhancement, gssoc25, Level 3

#71 Fixed the Roadmap Counter issue
  client/src/pages/Roadmap.jsx
Labels: enhancement, gssoc25, Level 2

#77 feat(dashboard): Implement course enrollment and activity tracking
  client/src/components/UserActivity.jsx
  client/src/pages/CoursePlayer.jsx
  server/controllers/coursesController.js
  server/models/userActivitySchema.js
  server/routes/coursesRoute.js
Labels: enhancement, gssoc25, Level 3

#87 GSAP Animation & Responsiveness Update
  Readme.md
  client/package-lock.json
  client/package.json
  client/src/components/HomePageComponents/CallToAction.jsx
  client/src/components/HomePageComponents/ChooseUs.jsx
  client/src/components/HomePageComponents/Contributor.jsx
  client/src/components/HomePageComponents/CreatorsContainer.jsx
  client/src/components/HomePageComponents/FAQ.jsx
  client/src/components/HomePageComponents/NewsLetter.jsx
  client/src/components/HomePageComponents/Testimonials.jsx
  client/src/components/NavBar.jsx
  client/src/pages/Home.jsx
  client/src/utils/Counter.jsx
Labels: enhancement, Style Enhancement, gssoc25, Level 3

#92 Forgot password reset page
  client/src/App.jsx
  client/src/pages/ForgotPassword.jsx
  client/src/pages/testLogin.jsx
  server/.env.example
  server/controllers/authController.js
  server/package-lock.json
  server/routes/authRouter.js
Labels: enhancement, gssoc25, Level 3

#96 Background Image Overlapping with Navbar
  client/src/pages/Home.jsx
Labels: enhancement, gssoc25, Level 2

#114 Implemted Bookmark feature & Bookmark page for Roadmaps
  client/src/App.jsx
  client/src/components/NavBar.jsx
  client/src/pages/Bookmarks.jsx
  client/src/pages/Roadmap.jsx
  server/controllers/bookmarkController.js
  server/models/userSchema.js
  server/routes/bookmarkRoute.js
  server/server.js
Labels: enhancement, gssoc25, Level 3

#123 Update single button for login/signup in navbar
  client/src/components/NavBar.jsx
Labels: enhancement, good first issue, gssoc25, Level 1

#129 custom cursor
  client/public/cursor-button.svg
  client/public/cursor-input.svg
  client/public/cursor-white.svg
  client/public/cursor.svg
  client/src/App.css
  client/src/index.css
Labels: enhancement, gssoc25, Level 2

#151 Update the design of Dashboard Page to match Roadmaps UI
  client/src/pages/Dashboard.jsx
Labels: enhancement, gssoc25, Level 3
